INFO     root:test_address_dispose.py:50 --------正在执行删除收货地址操作！ --------
INFO     root:common_driver.py:42 -------当前浏览器是：chrome-------
INFO     root:common_driver.py:55 -------重新置空driver-------
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA61741C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/7f04ac10c192754260f2f59158b98e20/element
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA601F308>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/7f04ac10c192754260f2f59158b98e20/element
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA6179088>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/7f04ac10c192754260f2f59158b98e20/element
INFO     root:test_address_dispose.py:50 --------正在执行删除收货地址操作！ --------
INFO     root:common_driver.py:42 -------当前浏览器是：chrome-------
INFO     root:common_driver.py:55 -------重新置空driver-------
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA6292848>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ead97ee7f34c73a2c38cbc6f06f4b5/element
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA62405C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ead97ee7f34c73a2c38cbc6f06f4b5/element
WARNING  urllib3.connectionpool:connectionpool.py:811 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DCA605F708>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b8ead97ee7f34c73a2c38cbc6f06f4b5/element